#!/bin/bash
for hook_path in "$(dirname "$0")/$(basename "$0").d"/*; do
    if [ -x "$hook_path" ]; then
        "$hook_path" "$@"
    fi
done

local_git_hook_path="$(git rev-parse --git-dir)"/hooks/"$(basename "$0")"

if [ -x "$local_git_hook_path" ]; then
    "$local_git_hook_path" "$@"
fi

if [ "$USING_HUSKY" ]; then
    husky_git_hook_path="$(git rev-parse --show-toplevel)"/.husky/_/"$(basename "$0")"
    husky_git_hook_path_8="$(git rev-parse --show-toplevel)"/.husky/"$(basename "$0")"

    if [ -x "$husky_git_hook_path" ]; then
        "$husky_git_hook_path" "$@"
    fi

    if [ -x "$husky_git_hook_path_8" ]; then
        "$husky_git_hook_path_8" "$@"
    fi
fi
